modLoader = "javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false

issueTrackerURL = "https://github.com/${github}/${name}/issues"

[[mods]]
modId="${id}"
version="${version}"
displayName="${display_name}"
authors="${author}"
description="${description}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL = "https://github.com/${github}/${name}/"

[[mixins]]
config = "mixins.${id}.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="${mc}"
ordering="NONE"
side="BOTH"